# fly.toml app configuration file generated for phonic-rockstar-mobile-demo on 2025-05-22T01:40:49Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'phonic-rockstar-mobile-demo'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
